### ISSUE TITLE
hdfs data nodes customization

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/mantl-hdfs#1]
@ryane how do I customize how many data nodes I want to start? What are my options here?
I saw DCOS repo and they have it in config.json , but i see nothing in this MANTL repo for hdfs.

**Comment by ryane** [comment]
the hdfs framework is difficult to configure. you probably need to change some settings in the mesos-site.xml. see https://github.com/mesosphere/hdfs/blob/0.1.4/conf/mesos-site.xml. you can use the custom-config (set it to your base64 encoded mesos-site.xml content) option when installing the framework via mantl-api. I am not sure if it matters for this scenario (I haven’t tried adjusting the number of nodes) but there is a problem where the custom mesos-site.xml is not distributed to executors. Unfortunately the repo/issue describing it has been removed. it used to be here: mesosphere/dcos-hdfs#5. so, the other option would be to build hdfs-mesos with your desired config and change the framework config to use your custom package. see https://github.com/mesosphere/hdfs#building-hdfs-mesos

This repo is based on a deprecated version of the hdfs package so you may be better off checking out the new version. But, afaik, it hasn't been tested on mantl at all.

**Comment by zoza1982** [comment]
thanks @ryane .
Yeah the version which MANTL uses does not have option anywhere for data node count in *-site.xml files. The new version has. Version which mantl uses will start data node automatically on any new nodes that is beyond 4 nodes ( 4 are used/reserved  by zk and namenodes) .

E.g So if you have total 6 nodes it will start 2 data nodes.  Every other node added into mesos cluster, this framework version will start new hadoop data node on that new node.
